apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logstash
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: logstash
    spec:
      containers:
      - image: logstash:7.8.0
        imagePullPolicy: ""
        name: logstash
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/logstash/pipeline/
          name: mdm-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: mdm-data
        persistentVolumeClaim:
          claimName: mdm-data
status: {}
