apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mastery-data-manager
  name: mastery-data-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mastery-data-manager
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: mastery-data-manager
    spec:
      containers:
      - image: dirtboy/cn-mastery-data-manager:latest
        imagePullPolicy: ""
        name: mastery-data-manager
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
