apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ubuntu
  name: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ubuntu
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: ubuntu
    spec:
      containers:
      - image: ubuntu:18.04
        imagePullPolicy: ""
        name: ubuntu
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
