apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-config
data:
  bootstrap.memory_lock: false
  discovery.zen.ping.unicast.hosts: "['host1':10.56.2.0, 'host2':10.56.0.0, 'host3':10.56.1.0]"
  discovery.zen.minimum_master_nodes: 1
  xpack.security.enabled: false
  xpack.monitoring.enabled: false
