apiVersion: apps/v1
kind: Deployment
metadata:
  name: gclassroom-logging
  namespace: elastic-system
  labels:
    k8s-app: gclassroom-logging
spec:
  replicas: 1
  selector:
    matchLabels:
            k8s-app: gclassroom-logging
  template:
    metadata:
      labels:
              k8s-app: gclassroom-logging
    spec:
      containers:
      - name: gclassroom-logging
        image: dirtboy/cn-mastery-data-manager:2.0
