apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: kube-system
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    input {
      beats {
        port => 5044
        }
    }

    filter {
        grok {
          patterns_dir => "./patterns"
          match => { "message" => "%{COURSE_ID:courseId} \ %{COURSE_NAME:courseName} \ %{COURSEWORK_ID:courseWorkId} \ %{COURSEWORK_TITLE:courseWorkTitle} \ %{COURSEWORK_DESCRIPTION:courseWorkDescription} \ %{COURSEWORK_ALTERNATELINK:courseWorkAlternateLink} \ %{COURSEWORK_CREATIONTIME: courseWorkCreationTime} \ %{SUBMISSION_ID:submissionId} \ %{SUBMISSION_STUDENT_ID:studentId} \ %{SUBMISSION_ALTERNATELINK:submissionAlternateLink}"}
          }
        }

    output {
      elasticsearch {
        hosts => ["elasticsearch-logging:9200"]
      }
    } 

