filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false
    setup.ilm.enabled: false

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.logstash:
  hosts: [“34.82.224.149:9600”]
